bus:
  schema:
    transport:
      redis:
        url: "redis://127.0.0.1:6379/0"
apis:
  default:
    event_transport:
      redis:
        url: "redis://127.0.0.1:6379/0"
        rpc_timeout: 15 
    rpc_transport:
      redis:
        url: "redis://127.0.0.1:6379/0"
        rpc_timeout: 15 
        rpc_retry_delay: 1
    result_transport:
      redis:
        url: "redis://127.0.0.1:6379/0"
        rpc_timeout: 15 
        rpc_retry_delay: 1
