version: 1
disable_existing_loggers: false

formatters:
    standard:
        format: "%(asctime)s::%(name)s::%(levelname)s::%(message)s"
    error:
        format: "%(asctime)s %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    rich_console:
        class: rich.logging.RichHandler
        rich_tracebacks: True
        level: DEBUG

    trader_service_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /home/trader/mmr/logs/trader_service.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    strategy_service_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /home/trader/mmr/logs/strategy_service.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    worker_service_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /home/trader/mmr/logs/worker_service.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /home/trader/mmr/logs/trader.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /home/trader/mmr/logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /tmp/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: NOTSET
    handlers: [rich_console, file_handler, error_file_handler, debug_file_handler]

loggers:
    worker_service:
        level: DEBUG
        handlers: [worker_service_handler, error_file_handler]
        propogate: no
    ib_history:
        level: DEBUG
        handlers: [worker_service_handler, error_file_handler]
        propogate: no
    trader_service:
        level: DEBUG
        handlers: [trader_service_handler, error_file_handler]
        propogate: no
    trading_runtime:
        level: DEBUG
        handlers: [trader_service_handler, error_file_handler]
        propogate: no
    strategy_service:
        level: DEBUG
        handlers: [strategy_service_handler, error_file_handler]
        propogate: no
    strategy_runtime:
        level: DEBUG
        handlers: [strategy_service_handler, error_file_handler]
        propogate: no
