env: TRADER_CHECK=False
strategies:
  - name: global
    description: strategy wide configuration
    universe: portfolio
    bar_size: '1 min'
    historical_days_prior: 90
    module: strategies/global.py
    class_name: Global
    paper: False
