root_directory: /home/trader/mmr
config_file: /home/trader/mmr/configs/trader.yaml
lightbus_config_file: /home/trader/mmr/configs/lightbus.yaml
lightbus_module: trader.messaging.bus
pycron_config_file: /home/trader/mmr/configs/pycron.yaml
logfile: logs/trader.log
ib_server_address: 127.0.0.1
ib_server_port: 7496
ib_client_id: 5
arctic_server_address: 127.0.0.1
arctic_library: 'Historical'
redis_server_address: 127.0.0.1
redis_server_port: 6379
pycron_server_address: 127.0.0.1
pycron_server_port: 8081
