root_directory: /home/trader/mmr
config_file: /home/trader/mmr/configs/trader.yaml
pycron_config_file: /home/trader/mmr/configs/pycron.yaml
strategy_config_file: /home/trader/mmr/configs/strategy_runtime.yaml
logfile: logs/trader.log
strategies_directory: /home/trader/mmr/strategies
trading_mode: live
ib_server_address: 127.0.0.1
ib_server_port: 7496
trading_runtime_ib_client_id: 5
strategy_runtime_ib_client_id: 7
arctic_server_address: 127.0.0.1
arctic_universe_library: 'Universes'
arctic_configuration_library: 'Configuration'
arctic_financials_library: 'Financials'
redis_server_address: 127.0.0.1
redis_server_port: 6379
pycron_server_address: 127.0.0.1
pycron_server_port: 8081
zmq_rpc_server_address: tcp://127.0.0.1
zmq_rpc_server_port: 42001
zmq_pubsub_server_address: tcp://127.0.0.1
zmq_pubsub_server_port: 42002
zmq_strategy_rpc_server_address: tcp://127.0.0.1
zmq_strategy_rpc_server_port: 42005
zmq_messagebus_server_address: tcp://127.0.0.1
zmq_messagebus_server_port: 42006