root_directory: /home/trader/mmr
config_file: /home/trader/mmr/configs/trader.yaml
pycron_config_file: /home/trader/mmr/configs/pycron.yaml
strategy_config_file: /home/trader/mmr/configs/strategy_runtime.yaml
logfile: logs/trader.log
strategies_directory: /home/trader/mmr/strategies
trading_mode: live
# your IB account can be set here, or via environment variable "IB_ACCOUNT"
# if you're trading your paper account, you'll need to switch trading_mode: paper,
# and set your paper account number here
ib_account:
ib_server_address: 127.0.0.1
ib_server_port: 7496
trading_runtime_ib_client_id: 5
strategy_runtime_ib_client_id: 7
# your polygon.io account API key can be set here, or via environment variable
# "POLYGON_API_KEY". The polygon.io account isn't necessary to run mmr
polygon_api_key:
arctic_server_address: 127.0.0.1
arctic_universe_library: 'Universes'
arctic_configuration_library: 'Configuration'
arctic_financials_library: 'Financials'
redis_server_address: 127.0.0.1
redis_server_port: 6379
pycron_server_address: 127.0.0.1
pycron_server_port: 8081
zmq_rpc_server_address: tcp://127.0.0.1
zmq_rpc_server_port: 42001
zmq_pubsub_server_address: tcp://127.0.0.1
zmq_pubsub_server_port: 42002
zmq_strategy_rpc_server_address: tcp://127.0.0.1
zmq_strategy_rpc_server_port: 42005
zmq_messagebus_server_address: tcp://127.0.0.1
zmq_messagebus_server_port: 42006